### ISSUE TITLE
提示这个信息呢 

### ISSUE THREAD

**Issue by chaodada** [adamyi/wechrome#2]
<error><ret>1203</ret><message>当前微信版本过低，请升级至最新版本。</message></error>

**Comment by chaodada** [comment]
`<error><ret>1203</ret><message>当前微信版本过低，请升级至最新版本。</message></error>`

**Comment by phoenixxie7** [comment]
应该是你的浏览器跳转到wx2.qq.com了吧。

**Comment by adamyi** [comment]
This is a duplicate issue of #1 and should be resolved with #5. Please re-open this and let me know if it still doesn't work on the latest HEAD
