### ISSUE TITLE
Can you put it on the chrome store?

### ISSUE THREAD

**Issue by lqzhgood** [adamyi/wechrome#6]
Can you put it on the chrome store ?

If you don't have a chrome store account, I can help.

**Comment by adamyi** [comment]
I do have a Chrome store account.

Was a bit concerned previously that if I put it to the Chrome webstore so it's easier to install, it might get more exposure for Tencent to act against it.

But yeah I'm happy to push it to Chrome store this weekend

**Comment by lqzhgood** [comment]
Your worry is really.
It should be treated with caution.
It doesn't matter much not to put.

**Comment by lqzhgood** [comment]
Thank you for your coding。
