### ISSUE TITLE
still display cannot login web wechat

### ISSUE THREAD

**Issue by Yansongsongsong** [adamyi/wechrome#7]
i logged in with android, after i scan web QRcode, it find that 
```
你的账号无法登录网页版Wechat
```

and then toast one message:
```
微信：查找失败(4, -1)
```

**Comment by YungAncestor** [comment]
除HK/MO外WeChat账号所在的新加坡服务器（sg,support.wechat.com/sgshort.wechat.com）已经关闭了网页版功能。需要使用可以换绑852或853迁移到香港服务器hksupport.weixin.qq.com即可扫码确认登录

**Comment by wenkangmq** [comment]
20211126，澳洲，Fedora35亲测可用，比之前装修改header插件再添加rules要方便许多。我就不开新post了。谢谢！

**Comment by jyoui** [comment]
2021 11 30, 东京，Windows 10， 亲测可用。

谢谢！  可以在浏览器上绕不开时使用下微信了

**Comment by Wildlamb517** [comment]
这个如何使用呢？

**Comment by FiberStudio** [comment]
> 这个如何使用呢？

master分支下的代码就是个浏览器插件，在chrome浏览器中，设置--更多--拓展程序--加载已解压的拓展程序即可

**Comment by FiberStudio** [comment]
感谢，2021.12，+86绑定，亲测可用

**Comment by shikkoku** [comment]
上午还能用，下午提示网络错误被登出，再次扫码登录仅提示 ”登陆失败。”

**Comment by sgl123github** [comment]
我的目前也提示登录失败

**Comment by tangli159** [comment]
我偶尔提示登录失败，但是不知是不是因为我的网页版微信已经解禁，不管开不开拓展，都可以登陆成功，手机上只提示网页微信已登录，不会提示桌面版微信。。

**Comment by FiberStudio** [comment]
前天用还好好的，今天突然就登录不了了。扫码后显示登录失败。看来微信是铁了心要封禁网页登录了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月31日(星期五) 下午3:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [adamyi/wechrome] still display cannot login web wechat (#7)





 
我偶尔提示登录失败，但是不知是不是因为我的网页版微信已经解禁，不管开不开拓展，都可以登陆成功，手机上只提示网页微信已登录，不会提示桌面版微信。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tangxiaofeng7** [comment]
GG

**Comment by adamyi** [comment]
Duplicate with #9, which is now resolved.
