### ISSUE TITLE
web微信登录失败

### ISSUE THREAD

**Issue by JustinSunli** [adamyi/wechrome#9]
web微信登录失败

**Comment by chenchenchenze** [comment]
<error><ret>1203</ret><message>登录失败。</message></error>

**Comment by chenchenchenze** [comment]
\<error\>\<ret\>1203\<\/ret\>\<message\>登录失败。\<\/message\>\<\/error\>

**Comment by ouyen** [comment]
UOS微信更新了，旧方法失效了

**Comment by wohaoa** [comment]
目前有什么方法可以登入么？

**Comment by bennyrhys** [comment]
当前方法失效了，2021年末还能用，22年初失效了

**Comment by Neo-peng** [comment]
之前能用，现在失效的+1

**Comment by MrPeterJin** [comment]
当前方法失效+1

**Comment by bruce21cn** [comment]
当前方法失效了，2021年末还能用，22年初失效了，顶更新

**Comment by iscaswang** [comment]
求更新可用的版本，谢谢

**Comment by dreamncn** [comment]
This PR has fixed the problem #10

**Comment by adamyi** [comment]
I've merged ^. Thanks @dreamncn !
